### ISSUE TITLE
How to play recorded Data with different resolution

### ISSUE THREAD

**Issue by PhilippHandle** [ineventapp/musjs#1]
Currently i build a small frontend plugin to play recorded Data.
If i set the data in smaller/bigger window the click get messed up.

open http://htmlpreview.github.io/?https://github.com/ineventapp/musjs/blob/master/example.html
Record something and make the window smaller -> messed up

**Comment by mauriciogior** [comment]
You need to use `setWindowSize(width, height)` for your specific window size.
