### ISSUE TITLE
Add elapsed time for each data point

### ISSUE THREAD

**Issue by jv2222** [ineventapp/musjs#2]
Great work!

**Comment by jv2222** [comment]
Ah, I did find one small issue in that it doesn't record/play back in real time. 

Can you think of a way to make it play back in real time (as recorded)?

Thanks for an awesome lib!

**Comment by jv2222** [comment]
Hmm. I see. I think we would need to abstract `self.frames.push(scroll); and `self.frames.push(click);` to go through a stableTime function that inserts to frames that are pre-mapped out to 10th of seconds or 1/2 seconds. Will have a think and a play.

**Comment by jv2222** [comment]
of course, when you dig a little deeper it's never as easy as you first think. now we need to consider time drift.

https://stackoverflow.com/questions/29971898/how-to-create-an-accurate-timer-in-javascript

**Comment by jv2222** [comment]
Well, of course, it's a lot more complicated than it looks to create real time record and play back. 

Some discussion on the subject:

- https://stackoverflow.com/questions/29971898/how-to-create-an-accurate-timer-in-javascript/29972322#29972322

- https://stackoverflow.com/questions/46922880/js-interval-accurate-to-1ms

**Comment by mauriciogior** [comment]
Yeah it is, I decided to record elapsed time a single time and distribute evenly for all data points. I'll add an option to store elapsed time for each data point for more accurate data.

**Comment by mauriciogior** [comment]
Released on https://github.com/ineventapp/musjs/releases/tag/v1.1.0

**Comment by jv2222** [comment]
Nice work!
