### ISSUE TITLE
Download of recording

### ISSUE THREAD

**Issue by GaiaCo** [ineventapp/musjs#8]
Hello, 
I was looking for a way to record mouse trajectory during a jsPsych experiment done remotely and your library does it beautifully! 
I would like to download the "video" created onto an exportable file - is this possible? and if so, how?

I am sorry if this is a stupid question but I am fairly new to JavaScript and programming in general. 

Thank you in advance :)

**Comment by mauriciogior** [comment]
Hi @GaiaCo, I'm happy to hear that. This library simply records your mouse x and y position at a certain time and generates a json array with all mouse changes during a period of time. It also has a function to read the generate data and simulate the mouse movements and clicks by manipulating the x and y position of an svg image that represents a cursor and also manipulating scroll and click events.

To generate an actual video recording of your screen, you'd need to use other libraries that can render the mouse tracking movement on your window to a video file.

The purpose of this library is to generate lightweight representations of an user's mouse during a session in your webpage.

I hope this helps.

**Comment by GaiaCo** [comment]
Thank you for the fast answer! Ok, nice to know, I will keep on looking then, thanks! ;)
